include:
  - board: nice_nano_v2
    shield: velvet_left
    snippet: studio-rpc-usb-uart nrf52840-nosd
  - board: nice_nano_v2
    shield: velvet_right
    snippet: nrf52840-nosd
  - board: nice_nano_v2
    shield: settings_reset
