name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "keymap-drawer"
      destination: "both"
      parse_args: "" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "" # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
      debug_mode: true
  create_png:
    runs-on: ubuntu-latest
    needs:
      - draw
    steps:
      - name: Install PNG Image Tools
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y imagemagick
          sudo apt-get install -qq -y inkscape
          echo "which convert"
          which convert
          echo "convert --version"
          convert --version
      - uses: actions/checkout@v4
      - run: |
          git checkout -b ${{ github.ref_name }}
          git config --global user.email "linrongbin16@outlook.com"
          git config --global user.name "linrongbin16"
          git pull
      - name: Generate PNG
        run: |
          # Use 5x times density for bigger PNG, by default is 96
          convert -density 480 ./keymap-drawer/velvet.svg ./keymap-drawer/velvet.png
          echo "git status"
          git status
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(png): auto-create png image"
          file_pattern: "keymap-drawer/velvet.png"
